import { Injectable } from '@angular/core';
import { LanguageEnum } from 'src/app/enums/language-enum';

@Injectable({
  providedIn: 'root'
})
export class TranslateServiceService {
  hebrewDico: Dictionary<string> = {
    ["price"]: 'מחיר',
    ["Shirts & Tops"]: 'חולצות',
    ["Pants & Bottoms"]: 'מכנסיים',
    ["Coats & Jackets"]: 'מעילים & ג׳קטים',
    ["Dresses"] : 'שמלות',
    ["Shoes & Bags"] : 'נעליים & תיקים',
    ["Accessories"]:'אקססוריז',
    ["Add to cart"]:'הוסף לעגלה',
    ["Description"]: 'תיאור',
    ["Choose size"]: 'בחירת מידה',
    ["Choose quantity"]: 'בחירת כמות',
    ["Cart is empty!"]: 'העגלה ריקה!',
    ["Total: "]: 'סה״כ :',
    ["To Payment :"]: 'לתשלום :',
    ["Need help? Ask us"]: 'צריך עזרה? פנה אלינו',
    ["Payment text"]: "ההזמנה תאושר סופית לאחר התשלום באמתעות אחת הפלטפורמות הבאות למספר המופיע מטה. תוכל לעקוב אחרי סטטוס ההזמה. לכל שאלה פנה אלינו בווטסאפ בקישור למטה: ",
    ["Whatsapp"]: "שלום, יש לי שאלה...",
    ["Phone to pay :"]: "מספר טלפון לתשלום (ספיר עוזר) :",
    ["PayWay :"]: "תשלום :",
    ["Choose color :"]: "בחר צבע:",
    ["Was Added Successfully to cart!"]: " התווסף לעגלה בהצלחה!",
    ["Close"]: "סגור",
    ["purple"]: "סגול",
    ["red"]: "סגול",
    ["green"]: "ירוק",
    ["yellow"]: "צהוב",
    ["bronze"]: "נחושת",
    ["gold"]: "זהב",
    ["orange"]: "כתום",
    ["silver"]: "כסף",
    ["black"]: "שחור",
    ["white"]: "לבן",
    ["beige"]: "בז׳",
    ["brown"]: "חום",
    ["blue"]: "כחול",
    ["grey"]: "אפור",
    ["rose"]: "ורוד",
    ["camel"]: "קאמל",
    ["signin"]: "התחבר",
    ["signup"]: "הירשם",
    ["email"]: "אימייל:",
    ["password"]: "סיסמא:",
    ["confirm password"]: "אישור סיסמא:",
    ["forgot password"]: "שחכתי סיסמא",
    ["enter"]: "כניסה!",
    ["not a member"]: "עדיין לא הצטרפת? ",
    ["join us"]: "הירשם כאן",
    ["password not same"]: "הסיסמאות לא תואמות!",
    ["password error"]:"הסיסמא צריכה להיות לפחות 8 תווים!",
    ["mail error"]: "אימייל לא תקין!",
    ["something went wrong"]: "משהו השתבש!",
    ["got it"]: "הבנתי!",
    ["oops"]: "אופס!",
    ["confirm order"]: "אישור ההזמנה",
    ["first name"]: "שם פרטי:",
    ["last name"]: "שם משפחה:",
    ["phone number"]: "מספר טלפון:",
    ["street"]: "רחוב:",
    ["house number"]: "מספר בית:",
    ["city"]: "שם עיר:",
    ["postal code"]: "מיקוד:",
    ["fname error"]: "שם פרטי חסר!",
    ["lname error"]: "שם משפחה חסר!",
    ["email error"]: "אימייל לא תקין!",
    ["phone error"]: "מספר טלפון לא תקין!",
    ["street error"]: "שם רחוב חסר!",
    ["house error"]: "מספר בית חסר!",
    ["city error"]: "שם עיר חסר!",
    ["postal error"]: "מיקוד חסר!",
    ["send"]: "שלח!",
    ['address']: "כתובת מלאה:",
    ['address error']: "כתובת חסרה!",
    ["Order number: "]: "הזמנה מספר: ",
    ["Was created Successfully!"]: " נוצרה בהצלחה! ",
    ["Account"]: "החשבון שלי",
    ["item"]:"פריט: ",
    ["image"]: "תמונה: ",
    ["quantity"]: "כמות: ",
    ["size"]: "מידה: ",
    ["total"]: "סה״כ: ",
    ["price2"]: "מחיר: ",
    ["delete"]: "הסר",
    ["delete confirmation"]: "הסרת פריט מהעגלה",
    ["are you sure to delete"]: "האם הנך בטוח שברצונך למחוק מהעגלה את ",
    ["item has been removed"]: "הפריט הוסר מהעגלה!",
    ["cancel"]: "ביטול",
    ["track order"]: "להזמנה שלי",
    ["order date"]: "תאריך ההזמנה:",
    ["order status"]: "סטטוס ההזמנה:",
    ["order details"]: "פרטי ההזמנה:",
    ["order total"]: "סכום ההזמנה:",
  };
  englishDico: Dictionary<string> = {
    ["price"]: 'price',
    ["Shirts & Tops"]: 'Shirts & Tops',
    ["Pants & Bottoms"]: 'Pants & Bottoms',
    ["Coats & Jackets"]: 'Coats & Jackets',
    ["Dresses"] : 'Dresses',
    ["Shoes & Bags"] : 'Shoes & Bags',
    ["Accessories"]:'Accessories',
    ["Add to cart"]: 'Add to cart',
    ["Description"]: 'Description',
    ["Choose size"]: 'Choose size',
    ["Choose quantity"]: 'Choose quantity',
    ["Cart is empty!"]: 'Cart is empty!',
    ["Total: "]: "Total: ",
    ["To Payment :"]: "To Payment :",
    ["Need help? Ask us"]: "Need help? Ask us",
    ["Payment text"]: "The order will be finally confirmaed after the payment via one of the following payment platform. You can track you order status at anytime. For any question, ask us on Whatsapp, on the link",
    ["Whatsapp"]: "Hi, I have a question ...",
    ["Phone to pay :"]: "Phone number to make payment (Sapir Ozer)",
    ["PayWay :"]: "Payment :",
    ["Choose color :"]: "Choose color :",
    ["Was Added Successfully to cart!"]:"Was Added Successfully to cart!",
    ["Close"]: "Close",
    ["purple"]: "purple",
    ["red"]: "red",
    ["green"]: "green",
    ["yellow"]: "yellow",
    ["bronze"]: "bronze",
    ["gold"]: "gold",
    ["beige"]: "beige",
    ["orange"]: "orange",
    ["silver"]: "silver",
    ["black"]: "black",
    ["white"]: "white",
    ["brown"]: "brown",
    ["blue"]: "blue",
    ["grey"]: "grey",
    ["rose"]: "rose",
    ["camel"]: "camel",
    ["signin"]: "Sign-In",
    ["signup"]: "Sign-Up",
    ["email"]: "Email:",
    ["password"]: "Passsword:",
    ["confirm password"]: "Confirm Password: ",
    ["forgot password"]: "Forgot Password? ",
    ["enter"]: "Enter!",
    ["not a member"]: "Not a member? ",
    ["join us"]: "Join us",
    ["password not same"]: "Password are not the same!",
    ["password error"]:"Password must be aat least 8 characters!",
    ["mail error"]: "Email is invalid!",
    ["something went wrong"]: "Something went wrong! Try again!",
    ["got it"]: "I got it!",
    ["oops"]: "Oops!",
    ["confirm order"]:"Order Confirmation",
    ["first name"]: "First Name:",
    ["last name"]: "Last Name:",
    ["phone number"]: "Phone Number:",
    ["street"]: "Street:",
    ["house number"]: "House Number:",
    ["city"]: "City:",
    ["postal code"]: "Postal Code:",
    ["fname error"]: "First Name is empty!",
    ["lname error"]: "Last Name is empty!",
    ["email error"]: "Email is invalid!",
    ["phone error"]: "Phone Number is invalid!",
    ["street error"]: "Street Name is empty!",
    ["house error"]: "House Number is empty!",
    ["city error"]: "City is empty!",
    ["postal error"]: "Postal Code is invalid!",
    ["send"]:"Send!",
    ['address']: "Full Address: ",
    ['address error']: "Address is empty!",
    ["Order number: "]: "Order number :",
    ["Was created Successfully!"]: "Was created Successfully!",
    ["Account"]: "My Account",
    ["item"]:"Item:",
    ["image"]: "Image:",
    ["quantity"]: "Quantity:",
    ["size"]: "Size:",
    ["total"]: "Total:",
    ["price2"]: "Price:",
    ["delete"]: "Remove",
    ["delete confirmation"]: "Remove item from cart",
    ["are you sure to delete"]: "Are you sure to remove from cart ",
    ["item has been removed"]: "The item has been removed from cart!",
    ["cancel"]: "Cancel",
    ["track order"]: "View my order",
    ["order date"]: "Order Date:",
    ["order status"]: "Order Status:",
    ["order details"]: "Order Details:",
    ["order total"]: "Order Total:",
  };
  public currentLanguage: LanguageEnum = LanguageEnum.English;
  
  constructor() { }

  translate(word: string): string {
    if (this.currentLanguage === LanguageEnum.English) {
        return this.hebrewDico[word];
    } else {
      return this.englishDico[word];
    }
  }
}
